version: "3.9"
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: shelf
    ports: ["5432:5432"]
    volumes:
      - pgdata:/var/lib/postgresql/data
  backend:
    build: ./backend
    environment:
      DB_URL: ${DB_URL:-sqlite:///./shelf.db}
      JWT_SECRET: ${JWT_SECRET:-dev-secret-change}
      ADMIN_USERNAME: ${ADMIN_USERNAME:-admin}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD:-admin}
      UVICORN_HOST: 0.0.0.0
      UVICORN_PORT: 8000
    ports: ["8000:8000"]
    depends_on: [postgres]
volumes:
  pgdata:
