version: "3.9"
services:
  postgres:
    image: postgres:15
    container_name: shelf_postgres
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: shelf
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  backend:
    build: ./backend
    container_name: shelf_backend
    environment:
      DB_URL: postgresql://app:app@postgres:5432/shelf
      UVICORN_HOST: 0.0.0.0
      UVICORN_PORT: 8000
    depends_on:
      - postgres
    ports:
      - "8000:8000"
volumes:
  pgdata:
